export const ADD_NORM_USER = "ADD_NORM_USER";
export const ADD_USER_20 = "ADD_USER_20";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
